name: deploy

on:
  push:
    branches: [main] # main 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn install # 安装依赖

      - name: Build
        run: npm run build # 打包

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./build # 部署打包后的 dist 目录
          github_token: ${{ secrets.REACT_TOKEN }} # secret 名
          user_name: songxuyuan
          user_email: 541046145@qq.com
          commit_message: Update vue3-demo1 # 部署时的 git 提交信息，自由填写